export const cCode = {
AD:{n:"Andorra",l:"ca"},
AE:{en:"United Arab Emirates",n:"دولة الإمارات العربيّة المتّحدة",l:"ar"},
AF:{en:"Afghanistan",n:"د افغانستان اسلامي دولتدولت اسلامی افغانستان,جمهوری اسلامی افغانستان",l:"fa,ps"},
AG:{n:"Antigua and Barbuda",l:"en"},
AI:{n:"Anguilla",l:"en"},
AL:{en:"Albania",n:"Shqipëria",l:"sq"},
AM:{en:"Armenia",n:"Հայաստան",l:"hy"},
AO:{n:"Angola",l:"pt"},
AQ:{en:"Antarctica",n:"Antarctica,Antártico,Antarctique,Антарктике",l:"en,es,fr,ru"},
AR:{n:"Argentina",l:"es"},
AS:{n:"American Samoa",l:"en,sm"},
AT:{en:"Austria",n:"Österreich",l:"de"},
AU:{n:"Australia",l:"en"},
AW:{n:"Aruba",l:"nl,pap"},
AX:{en:"Aland Islands",n:"Åland",l:"sv"},
AZ:{en:"Azerbaijan",n:"Azərbaycan",l:"az"},
BA:{en:"Bosnia and Herzegovina",n:"Bosna i Hercegovina",l:"bs,hr,sr"},
BB:{n:"Barbados",l:"en"},
BD:{en:"Bangladesh",n:"গণপ্রজাতন্ত্রী বাংলাদেশ",l:"bn"},
BE:{en:"Belgium",n:"België,Belgique,Belgien",l:"nl,fr,de"},
BF:{n:"Burkina Faso",l:"fr"},
BG:{en:"Bulgaria",n:"България",l:"bg"},
BH:{en:"Bahrain",n:"البحرين",l:"ar"},
BI:{n:"Burundi",l:"fr"},
BJ:{en:"Benin",n:"Bénin",l:"fr"},
BL:{n:"Saint-Barthélemy",l:"fr"},
BM:{n:"Bermuda",l:"en"},
BN:{n:"Brunei Darussalam",l:"ms"},
BO:{en:"Bolivia",n:"Bolivia,Bulibiya,Volívia,Wuliwya",l:"es,qu,gn,ay"},
BQ:{en:"Caribbean Netherlands",n:"Caribisch Nederland",l:"nl"},
BR:{en:"Brazil",n:"Brasil",l:"pt"},
BS:{n:"Bahamas",l:"en"},
BT:{en:"Bhutan",n:"འབྲུག་ཡུལ",l:"dz"},
BV:{en:"Bouvet Island",n:"Bouvetøya",l:"no"},
BW:{n:"Botswana",l:"en,tn"},
BY:{en:"Belarus",n:"Беларусь",l:"be,ru"},
BZ:{n:"Belize",l:"en"},
CA:{n:"Canada",l:"en,fr"},
CC:{n:"Cocos (Keeling) Islands",l:"en"},
CD:{en:"Democratic Republic of the Congo (Congo-Kinshasa,former Zaire)",n:"République Démocratique du Congo",l:"fr"},
CF:{en:"Centrafrican Republic",n:"République centrafricaine,Ködörösêse tî Bêafrîka",l:"fr,sg"},
CG:{en:"Republic of the Congo (Congo-Brazzaville)",n:"République du Congo",l:"fr"},
CH:{en:"Switzerland",n:"Schweiz,Suisse,Svizzera,Svizra",l:"de,fr,it,rm"},
CI:{n:"Côte d'Ivoire",l:"fr"},
CK:{en:"Cook Islands",n:"Cook Islands,Kūki ʻĀirani",l:"en,rar"},
CL:{n:"Chile",l:"es"},
CM:{en:"Cameroon",n:"Cameroun,Cameroon",l:"fr,en"},
CN:{en:"China",n:"中国",l:"zh-hans"},
CO:{n:"Colombia",l:"es"},
CR:{n:"Costa Rica",l:"es"},
CU:{n:"Cuba",l:"es"},
CV:{n:"Cabo Verde",l:"pt"},
CW:{n:"Curaçao",l:"nl,en"},
CX:{n:"Christmas Island",l:"en"},
CY:{en:"Cyprus",n:"Κύπρος,Kibris",l:"el,tr"},
CZ:{en:"Czech Republic",n:"Česká republika",l:"cs"},
DE:{en:"Germany",n:"Deutschland",l:"de"},
DJ:{en:"Djibouti",n:"Djibouti,جيبوتي,Jabuuti,Gabuutih",l:"fr,ar,so,aa"},
DK:{en:"Denmark",n:"Danmark",l:"da"},
DM:{n:"Dominica",l:"en"},
DO:{en:"Dominican Republic",n:"República Dominicana",l:"es"},
DZ:{en:"Algeria",n:"الجزائر",l:"ar"},
EC:{n:"Ecuador",l:"es"},
EE:{en:"Estonia",n:"Eesti",l:"et"},
EG:{en:"Egypt",n:"مصر",l:"ar"},
EH:{en:"Western Sahara",n:"Sahara Occidental",l:"ar,es,fr"},
ER:{en:"Eritrea",n:"ኤርትራ,إرتريا,Eritrea",l:"ti,ar,en"},
ES:{en:"Spain",n:"España",l:"ast,ca,es,eu,gl"},
ET:{en:"Ethiopia",n:"ኢትዮጵያ,Itoophiyaa",l:"am,om"},
FI:{en:"Finland",n:"Suomi",l:"fi,sv,se"},
FJ:{n:"Fiji",l:"en"},
FK:{n:"Falkland Islands",l:"en"},
FM:{n:"Micronesia",l:"en"},
FO:{en:"Faroe Islands",n:"Føroyar,Færøerne",l:"fo,da"},
FR:{n:"France",l:"fr"},
GA:{n:"Gabon",l:"fr"},
GB:{n:"United Kingdom",l:"en,ga,cy,gd,kw"},
GD:{n:"Grenada",l:"en"},
GE:{en:"Georgia",n:"საქართველო",l:"ka"},
GF:{en:"French Guiana",n:"Guyane française",l:"fr"},
GG:{n:"Guernsey",l:"en"},
GH:{n:"Ghana",l:"en"},
GI:{n:"Gibraltar",l:"en"},
GL:{en:"Greenland",n:"Kalaallit Nunaat,Grønland",l:"kl,da"},
GM:{n:"The Gambia",l:"en"},
GN:{en:"Guinea",n:"Guinée",l:"fr"},
GP:{n:"Guadeloupe",l:"fr"},
GQ:{en:"Equatorial Guinea",n:"Guiena ecuatorial,Guinée équatoriale,Guiné Equatorial",l:"es,fr,pt"},
GR:{en:"Greece",n:"Ελλάδα",l:"el"},
GS:{n:"South Georgia and the South Sandwich Islands",l:"en"},
GT:{n:"Guatemala",l:"es"},
GU:{en:"Guam",n:"Guam,Guåhån",l:"en,ch"},
GW:{en:"Guinea Bissau",n:"Guiné-Bissau",l:"pt"},
GY:{n:"Guyana",l:"en"},
HK:{en:"Hong Kong (SAR of China)",n:"香港,Hong Kong",l:"zh-hant,en"},
HM:{n:"Heard Island and McDonald Islands",l:"en"},
HN:{n:"Honduras",l:"es"},
HR:{en:"Croatia",n:"Hrvatska",l:"hr"},
HT:{en:"Haiti",n:"Haïti,Ayiti",l:"fr,ht"},
HU:{en:"Hungary",n:"Magyarország",l:"hu"},
ID:{n:"Indonesia",l:"id"},
IE:{en:"Ireland",n:"Ireland,Éire",l:"en,ga"},
IL:{en:"Israel",n:"ישראל",l:"he"},
IM:{n:"Isle of Man",l:"en"},
IN:{en:"India",n:"भारत,India",l:"hi,en"},
IO:{n:"British Indian Ocean Territory",l:"en"},
IQ:{en:"Iraq",n:"العراق,Iraq",l:"ar,ku"},
IR:{en:"Iran",n:"ایران",l:"fa"},
IS:{en:"Iceland",n:"Ísland",l:"is"},
IT:{en:"Italy",n:"Italia",l:"it,de,fr"},
JE:{n:"Jersey",l:"en"},
JM:{n:"Jamaica",l:"en"},
JO:{en:"Jordan",n:"الأُرْدُن",l:"ar"},
JP:{en:"Japan",n:"日本",l:"ja"},
KE:{n:"Kenya",l:"sw,en"},
KG:{en:"Kyrgyzstan",n:"Кыргызстан,Киргизия",l:"ky,ru"},
KH:{en:"Cambodia",n:"កម្ពុជា",l:"km"},
KI:{n:"Kiribati",l:"en"},
KM:{en:"Comores",n:"ﺍﻟﻘﻤﺮي,Comores,Komori",l:"ar,fr,sw"},
KN:{n:"Saint Kitts and Nevis",l:"en"},
KP:{en:"North Korea",n:"북조선",l:"ko"},
KR:{en:"South Korea",n:"대한민국",l:"ko,en"},
KW:{en:"Kuwait",n:"الكويت",l:"ar"},
KY:{n:"Cayman Islands",l:"en"},
KZ:{en:"Kazakhstan",n:"Қазақстан,Казахстан",l:"kk,ru"},
LA:{en:"Laos",n:"ປະຊາຊົນລາວ",l:"lo"},
LB:{en:"Lebanon",n:"لبنان,Liban",l:"ar,fr"},
LC:{n:"Saint Lucia",l:"en"},
LI:{n:"Liechtenstein",l:"de"},
LK:{en:"Sri Lanka",n:"ශ්‍රී ලංකා,இலங்கை",l:"si,ta"},
LR:{n:"Liberia",l:"en"},
LS:{n:"Lesotho",l:"en,st"},
LT:{en:"Lithuania",n:"Lietuva",l:"lt"},
LU:{en:"Luxembourg",n:"Lëtzebuerg,Luxembourg,Luxemburg",l:"lb,fr,de"},
LV:{en:"Latvia",n:"Latvija",l:"lv"},
LY:{en:"Libya",n:"ليبيا",l:"ar"},
MA:{en:"Morocco",n:"Maroc,ⵍⵎⵖⵔⵉⴱ,المغرب",l:"fr,zgh,ar"},
MC:{n:"Monaco",l:"fr"},
MD:{en:"Moldova",n:"Moldova,Молдавия",l:"ro,ru,uk"},
ME:{en:"Montenegro",n:"Crna Gora,Црна Гора",l:"srp,sr,hr,bs,sq"},
MF:{en:"Saint Martin (French part)",n:"Saint-Martin",l:"fr"},
MG:{en:"Madagascar",n:"Madagasikara,Madagascar",l:"mg,fr"},
MH:{n:"Marshall Islands",l:"en,mh"},
MK:{en:"Macedonia (Former Yugoslav Republic of)",n:"Македонија",l:"mk"},
ML:{n:"Mali",l:"fr"},
MM:{en:"Myanmar",n:"မြန်မာ",l:"my"},
MN:{en:"Mongolia",n:"Монгол Улс",l:"mn"},
MO:{en:"Macao (SAR of China)",n:"澳門,Macau",l:"zh-hant,pt"},
MP:{n:"Northern Mariana Islands",l:"en,ch"},
MQ:{n:"Martinique",l:"fr"},
MR:{en:"Mauritania",n:"موريتانيا,Mauritanie",l:"ar,fr"},
MS:{n:"Montserrat",l:"en"},
MT:{n:"Malta",l:"mt,en"},
MU:{en:"Mauritius",n:"Maurice,Mauritius",l:"mfe,fr,en"},
MV:{n:"Maldives",l:"dv"},
MW:{n:"Malawi",l:"en,ny"},
MX:{n:"México",l:"es"},
MY:{n:"Malaysia",l:"ms"},
MZ:{n:"Mozambique",l:"pt"},
NA:{n:"Namibia",l:"en,sf,de"},
NC:{en:"New Caledonia",n:"Nouvelle-Calédonie",l:"fr"},
NE:{n:"Niger",l:"fr"},
NF:{n:"Norfolk Island",l:"en,pih"},
NG:{n:"Nigeria",l:"en"},
NI:{n:"Nicaragua",l:"es"},
NL:{en:"The Netherlands",n:"Nederland",l:"nl"},
NO:{en:"Norway",n:"Norge,Noreg",l:"nb,nn,no,se"},
NP:{n:"Nepal",l:"ne"},
NR:{n:"Nauru",l:"na,en"},
NU:{n:"Niue",l:"niu,en"},
NZ:{n:"New Zealand",l:"mi,en"},
OM:{en:"Oman",n:"سلطنة عُمان",l:"ar"},
PA:{n:"Panama",l:"es"},
PE:{n:"Perú",l:"es"},
PF:{en:"French Polynesia",n:"Polynésie française",l:"fr"},
PG:{n:"Papua New Guinea",l:"en,tpi,ho"},
PH:{n:"Philippines",l:"en,tl"},
PK:{en:"Pakistan",n:"پاکستان",l:"en,ur"},
PL:{en:"Poland",n:"Polska",l:"pl"},
PM:{en:"Saint Pierre and Miquelon",n:"Saint-Pierre-et-Miquelon",l:"fr"},
PN:{n:"Pitcairn",l:"en,pih"},
PR:{n:"Puerto Rico",l:"es,en"},
PS:{n:"Palestinian Territory",l:"ar,he"},
PT:{n:"Portugal",l:"pt"},
PW:{n:"Palau",l:"en,pau,ja,sov,tox"},
PY:{n:"Paraguay",l:"es,gn"},
QA:{en:"Qatar",n:"قطر",l:"ar"},
RE:{en:"Reunion",n:"La Réunion",l:"fr"},
RO:{en:"Romania",n:"România",l:"ro"},
RS:{en:"Serbia",n:"Србија",l:"sr,sr-Latn"},
RU:{en:"Russia",n:"Россия",l:"ru"},
RW:{n:"Rwanda",l:"rw,fr,en"},
SA:{en:"Saudi Arabia",n:"السعودية",l:"ar"},
SB:{n:"Solomon Islands",l:"en"},
SC:{n:"Seychelles",l:"fr,en,crs"},
SD:{en:"Sudan",n:"السودان",l:"ar,en"},
SE:{en:"Sweden",n:"Sverige",l:"sv"},
SG:{n:"Singapore",l:"zh-hans,en,ms,ta"},
SH:{n:"Saint Helena",l:"en"},
SI:{en:"Slovenia",n:"Slovenija",l:"sl"},
SJ:{n:"Svalbard and Jan Mayen",l:"no"},
SK:{en:"Slovakia",n:"Slovensko",l:"sk"},
SL:{n:"Sierra Leone",l:"en"},
SM:{n:"San Marino",l:"it"},
SN:{n:"Sénégal",l:"fr"},
SO:{en:"Somalia",n:"Somalia,الصومال",l:"so,ar"},
SR:{n:"Suriname",l:"nl"},
ST:{en:"São Tomé and Príncipe",n:"São Tomé e Príncipe",l:"pt"},
SS:{n:"South Sudan",l:"en"},
SV:{n:"El Salvador",l:"es"},
SX:{en:"Saint Martin (Dutch part)",n:"Sint Maarten",l:"nl,en"},
SY:{en:"Syria",n:"سوريا,Sūriyya",l:"ar"},
SZ:{n:"eSwatini",l:"en,ss"},
TC:{n:"Turks and Caicos Islands",l:"en"},
TD:{en:"Chad",n:"Tchad,تشاد",l:"fr,ar"},
TF:{en:"French Southern and Antarctic Lands",n:"Terres australes et antarctiques françaises",l:"fr"},
TG:{n:"Togo",l:"fr"},
TH:{en:"Thailand",n:"ประเทศไทย",l:"th"},
TJ:{n:"Tajikistan",l:"tg,ru"},
TK:{n:"Tokelau",l:"tkl,en,sm"},
TL:{en:"Timor-Leste",n:"Timor-Leste,Timor Lorosa'e",l:"pt,tet"},
TM:{en:"Turkmenistan",n:"Türkmenistan",l:"tk"},
TN:{en:"Tunisia",n:"تونس,Tunisie",l:"ar,fr"},
TO:{n:"Tonga",l:"en"},
TR:{en:"Turkey",n:"Türkiye",l:"tr"},
TT:{n:"Trinidad and Tobago",l:"en"},
TV:{n:"Tuvalu",l:"en"},
TW:{n:"Taiwan",l:"zh-hant"},
TZ:{n:"Tanzania",l:"sw,en"},
UA:{en:"Ukraine",n:"Україна",l:"uk"},
UG:{n:"Uganda",l:"en,sw"},
UM:{n:"United States Minor Outlying Islands",l:"en"},
US:{n:"United States of America",l:"en"},
UY:{n:"Uruguay",l:"es"},
UZ:{n:"Uzbekistan",l:"uz,kaa"},
VA:{en:"City of the Vatican",n:"Città del Vaticano",l:"it"},
VC:{n:"Saint Vincent and the Grenadines",l:"en"},
VE:{n:"Venezuela",l:"es"},
VG:{n:"British Virgin Islands",l:"en"},
VI:{n:"United States Virgin Islands",l:"en"},
VN:{en:"Vietnam",n:"Việt Nam",l:"vi"},
VU:{n:"Vanuatu",l:"bi,en,fr"},
WF:{en:"Wallis and Futuna",n:"Wallis-et-Futuna",l:"fr"},
WS:{n:"Samoa",l:"sm,en"},
YE:{en:"Yemen",n:"اليَمَن",l:"ar"},
YT:{n:"Mayotte",l:"fr"},
ZA:{n:"South Africa",l:"en,af,st,tn,xh,zu"},
ZM:{n:"Zambia",l:"en"},
ZW:{n:"Zimbabwe",l:"en,sn,nd"}
}